[package]
name = "dev_calagopus_mcpserver"
version = "1.3.1"
edition = "2024"
description = "Model Context Protocol (MCP) Connector extension for Calagopus game panel."
authors = ["Pato"]

[dependencies]
shared = { path = "../../shared" }
backend = { path = "../../backend" }
tokio = { workspace = true }
tracing = { workspace = true }
axum = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
utoipa = { workspace = true }
utoipa-axum = { workspace = true }
async-trait = { workspace = true }
anyhow = { workspace = true }
chrono = { workspace = true }
uuid = { workspace = true }
compact_str = { workspace = true }
semver = { workspace = true }
sqlx = { workspace = true }
futures-util = { workspace = true }
wings-api = { path = "../../api-clients/wings-api" }
reqwest = { workspace = true }
